numpy foundations 



numpy and practice


In [5]:
import numpy as np 

##Creting array from list

In [7]:
arr_1d=np.array([1,2,3,4,5,6])
print(arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)

[1 2 3 4 5 6]
2D array:  [[1 2 3]
 [4 5 6]]


difference between list vs numpy array 


In [9]:
py_list=[1,2,3]
print("python list multiplication", py_list*2)


np_array =np.array([1,2,3]) #element wise multiplication 
print("Python array Multiplication" ,np_array*2 )


import time 
start=time.time()
py_list=[i*2 for i in range (1000000)]
print("\n List operation time : ",time.time()-start )

start=time.time()
np_array=np.arange(1000000)*2
print("\n numpy operation time : ",time.time()-start )


python list multiplication [1, 2, 3, 1, 2, 3]
Python array Multiplication [2 4 6]

 List operation time :  0.08979249000549316

 numpy operation time :  0.009531259536743164


creating array from scratch 


In [11]:
zeros=np.zeros((3,4))
print("zeros array: \n", zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
ones=np.ones((3,6))
print("Ones array : \n",ones)

full=np.full((2,2),7)
print("full array:\n",full)

random=np.random.random((2,3))
print("random array:\n",random)

sequence=np.arange(0,10,2)
print("sequence array:\n",sequence)

Ones array : 
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
full array:
 [[7 7]
 [7 7]]
random array:
 [[0.67461063 0.50736123 0.4572034 ]
 [0.82473839 0.96433615 0.15161835]]
sequence array:
 [0 2 4 6 8]


vector ,matrix and tensor 

In [18]:
vector=np.array([1,2,3])
print("vector:",vector)

matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("matrix:",matrix)

tensor=np.array([[[1,2],[3,4]],
                 [[5,6],[7,8]]]) 
print("tensor:",tensor)


vector: [1 2 3]
matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array properties


In [20]:
arr=np.array([[1,2,3],
             [4,5,6]])
print("shape",arr.shape)
print("Dimension",arr.ndim)
print("size",arr.size)
print("Dtype",arr.dtype)

shape (2, 3)
Dimension 2
size 6
Dtype int64


array reshaping 


In [ ]:
arr=np.arange(12)
print("original array ",arr)

reshaped=arr.reshape((3,4))
print("reshaped array ",reshaped)

flattened=reshaped.flatten()
print("flatened array ",flattened)

raveled=reshaped.ravel()
print("raveled array ",raveled)

#Transpose 
transpose=reshaped.T
print("transposed array ",transpose)



original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flatened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]] ,
