numpy array operations


In [1]:
import numpy as np


In [2]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7])
print("With steps",arr[1:8:2])
print("NEgative indexing",arr[-3])

Basic Slicing [3 4 5 6 7]
With steps [2 4 6 8]
NEgative indexing 8


In [5]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific elements", arr_2d[1,2])
print("Entire row: ",arr_2d[1])
print("Entire row: ",arr_2d[:,1])





Specific elements 6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


sorting


In [10]:
unsorted=np.array([3,4,2,9,5,2,2,7,6,2,])
print("sorted array",np.sort(unsorted))

arr_2d_unsorted =np.array([[3,1],[1,2],[2,3]])
print("Sorted 2d array by column",np.sort(arr_2d_unsorted,axis=0))

sorted array [2 2 2 2 3 4 5 6 7 9]
Sorted 2d array by column [[1 1]
 [2 2]
 [3 3]]


filter

In [11]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers%2==0]
print("Even Numbers",even_number)


Even Numbers [ 2  4  6  8 10]


filter with mask

In [12]:
mask = numbers>5
print("Numbers greater than 5",numbers[mask])


Numbers greater than 5 [ 6  7  8  9 10]


fancy indexing vs np.where()

In [ ]:
indices= [0,2,4]
print(numbers[indices])
where_result=np.where(numbers>5)
print("NP where",numbers[where_result])

In [16]:
condition_Array=np.where(numbers > 5, numbers*4,numbers)
print(condition_Array)

[ 1  2  3  4  5 24 28 32 36 40]


adding and removing of data

In [18]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
combined =np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


array compatibility


In [19]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print("Compatiblity shapes", a.shape==b.shape)


Compatiblity shapes True


In [30]:
orginal=np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
with_new_row=np.vstack((orginal,new_row))
# print(orginal)
print(with_new_row)
new_col=np.array([[7],[8]])
with_new_col=np.hstack((orginal,new_col))
print("with new col", with_new_col)

[[1 2]
 [3 4]
 [5 6]]
with new col [[1 2 7]
 [3 4 8]]


In [31]:
arr=np.array([1,2,3,4,5,6])
deleted=np.delete(arr,2)
print(deleted)

[1 2 4 5 6]


advanced numpy 

In [37]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])
print("*** Zomato Sales analysis ***")
print("\n sales data shape",sales_data.shape)
print("\n Sample data for 1st 3 restaurant ",sales_data[:, 1:])


*** Zomato Sales analysis ***

 sales data shape (5, 5)

 Sample data for 1st 3 restaurant  [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


total sales per year

In [47]:
print(np.sum(sales_data,axis=0))
yearly_total=np.sum(sales_data[:,1:], axis=0)
print(yearly_total)

#minimum sales per restaurant 
min_sales=np.min(sales_data[:, 1:],axis=1)
print(min_sales)

# maximum sales per year
max_Sales=np.max(sales_data[:,1:],axis=0)
print(max_Sales)

#average sales per restaurant

avg_sales =np.mean(sales_data[:,1:],axis=1)
print(avg_sales)



[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]
[200000. 152500. 247500. 225000. 195000.]


In [48]:
#cumulative sum
cumsum=np.cumsum(sales_data[:,1:],axis=1)
print(cumsum)

[[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


In [52]:
vector1 =np.array([1,2,3,4,5])
vector2=np.array([6,7,8,9,10])
print("Vector add: ", vector1+vector2)
print("Vector multiplication ", vector1*vector2)

print("\n Dot product",np.dot(vector1,vector2))
angle=np.arccos(np.dot(vector1,vector2)/(np.linalg.norm(vector1)*np.linalg.norm(vector2)))
print(angle)

Vector add:  [ 7  9 11 13 15]
Vector multiplication  [ 6 14 24 36 50]

 Dot product 130
0.26554161733900966


In [53]:
restaurant_types = np.array(['biryani', 'chinese', 'pizza', 'burger', 'cafe'])
vectorized_upper =np.vectorize(str.upper)
print("Vectorized Upper",vectorized_upper(restaurant_types))

Vectorized Upper ['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']


In [55]:
monthly_avg=sales_data[:,1:] /12
print(monthly_avg)

[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
