this is pratice and revision for Numpy



In [2]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3,4])
print("1D array: ",arr1)

arr2=np.array([[1,2,3,4],[5,6,7,8]])
print("1D array: ",arr2)

zeros=np.zeros((2,3))
print("Zeros:\n",zeros)

ones=np.ones((3,3))
print("Ones: \n",ones)

range_arr=np.arange(0,10,2)
print("Range Array: ",range_arr)

linspace=np.linspace(0,10,5)
print("Linspace array : ",linspace)

1D array:  [1 2 3 4]
1D array:  [[1 2 3 4]
 [5 6 7 8]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Range Array:  [0 2 4 6 8]
Linspace array :  [ 0.   2.5  5.   7.5 10. ]


In [13]:
# Attributes of arr
print("Shape of arr2:", arr2.shape)  # (2, 3)
print("Size of arr2:", arr2.size)   # 6
print("Data type of arr2:", arr2.dtype)  # int32 (or similar)

# Attributes of linspace
print("Shape of linspace:", linspace.shape)  # (5,)
print("Size of linspace:", linspace.size)   # 5
print("Data type of linspace:", linspace.dtype)

Shape of arr2: (2, 4)
Size of arr2: 8
Data type of arr2: int64
Shape of linspace: (5,)
Size of linspace: 5
Data type of linspace: float64


In [36]:
#practice 1

oneD_array=([10,20,30,40,50])
print(oneD_array)
twod_arry=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(twod_arry)

zero_arr=np.zeros((3,2))
print(zero_arr)

one_arr=np.ones((3,2))
print(one_arr)


[10, 20, 30, 40, 50]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [37]:
rangee=np.arange(5,16,2)
print(rangee)

Linespace=np.linspace(0,10,6)
print(Linespace)

[ 5  7  9 11 13 15]
[ 0.  2.  4.  6.  8. 10.]


In [38]:
print("shape:", np.shape(twod_arry))
print("size:", np.size(twod_arry))
print("datatype:", twod_arry.dtype)

shape: (3, 3)
size: 9
datatype: int64


In [32]:
Crange=np.arange(0,12)
print(Crange)
reshaped=Crange.reshape(3,4)
print(reshaped)
reshaped.size
reshaped.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(3, 4)

In [35]:
import numpy as np

# Define the 2D array
twod_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print attributes
print("shape:", twod_array.shape)
print("size:", twod_array.size)
print("datatype:", twod_array.dtype)

shape: (3, 3)
size: 9
datatype: int64


In [40]:
#array operations 
arr=np.array([1,2,3,4])
print("ADD 2",arr+2)
print("multiply 2",arr*2)
print("division 2",arr/2)
print("square 2",arr**2)



ADD 2 [3 4 5 6]
multiply 2 [2 4 6 8]
division 2 [0.5 1.  1.5 2. ]
square 2 [ 1  4  9 16]


In [41]:
#operation between array
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print("add arrays",arr1+arr2)
print("multiply arrays",arr1*arr2)

add arrays [5 7 9]
multiply arrays [ 4 10 18]


In [42]:
# 2D arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A+B)
np.dot(A,B)

[[ 6  8]
 [10 12]]


array([[19, 22],
       [43, 50]])

In [43]:
#challenge question
array=np.arange(1,7)
Reshaped=array.reshape(2,3)
addition_arr=(Reshaped+10)*2
print(addition_arr)

[[22 24 26]
 [28 30 32]]


In [ ]:
##indexing and slicing 
arr1 = np.array([10, 20, 30, 40])
print("Element at index 1:", arr1[1])

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Element at row 0, column 1:", arr2[0, 1])
# 1D array slicing
print("Slice [1:3]:", arr1[1:3])  

# 2D array slicing
print("First row:", arr2[0, :]) 
print("Second column:", arr2[:, 1])
print("Subarray:", arr2[0:2, 1:3])

# Modify a single element
arr1[2] = 99
print("Modified arr1:", arr1)  

# Modify a slice
arr2[1, :] = [7, 8, 9]
print("Modified arr2:\n", arr2)  

Element at index 1: 20
Element at row 0, column 1: 2
Slice [1:3]: [20 30]
First row: [1 2 3]
Second column: [2 5]
Subarray: [[2 3]
 [5 6]]


In [59]:
# Challenge Question:
# Create a 1D array with values from 1 to 12 using np.arange().
# Reshape it into a 3x4 array.
# Extract the first two rows and the first three columns (resulting in a 2x3 array).
# Modify the element at row 1, column 2 of the extracted array to 99.
# Print the modified extracted array, its shape, and its size.

Array_1D=np.arange(1,13)
Array_reshaped=Array_1D.reshape(3,4)
print(Array_reshaped)
Extracted_rC=Array_reshaped[0:2,0:3]
print(Extracted_rC)
Extracted_rC[1,2]=99
print(Extracted_rC)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3]
 [5 6 7]]
[[ 1  2  3]
 [ 5  6 99]]


In [61]:
# Mathematical Functions
arr=np.array([1,4,9])
print("Square root:", np.sqrt(arr))
print("sine:", np.sin(arr))
print("exponential:", np.exp(arr))
print("natural log:", np.log(arr))


Square root: [1. 2. 3.]
sine: [ 0.84147098 -0.7568025   0.41211849]
exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03]
natural log: [0.         1.38629436 2.19722458]


In [63]:
# Statistical Functions
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print("Sum:", np.sum(arr2))      
print("Mean:", np.mean(arr2))     
print("Standard deviation:", np.std(arr2))

# Statistical functions along an axis
print("Sum along rows (axis=0):", np.sum(arr2, axis=0))  
print("Mean along columns (axis=1):", np.mean(arr2, axis=1))  

Sum: 21
Mean: 3.5
Standard deviation: 1.707825127659933
Sum along rows (axis=0): [5 7 9]
Mean along columns (axis=1): [2. 5.]


In [68]:
'''Challenge Question:
Create a 1D array with values from 1 to 12 using np.arange().
Reshape it into a 3x4 array.
Compute the square of each element in the array.
Calculate the mean of each column (along axis=0).
Print the squared array, the column means, and the shape of the squared array.'''

array=np.arange(1,13)
reshaped_Arr=array.reshape(3,4)
sqed_arr=np.square(reshaped_Arr)
print(sqed_arr)
array_mean0=np.mean(sqed_arr,axis=0)
array_meann0=np.mean(reshaped_Arr,axis=0)
print(array_mean0)
print(array_meann0)


[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[35.66666667 46.66666667 59.66666667 74.66666667]
[5. 6. 7. 8.]


In [69]:
import numpy as np
arr = np.array([1, 2, 3])
result = arr + 5  # 5 is "stretched" to [5, 5, 5]
print(result)  # [6, 7, 8]

[6 7 8]


In [70]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
arr1d = np.array([10, 20, 30])           # Shape (3,)
result = arr2d + arr1d                    # arr1d stretched to [[10, 20, 30], [10, 20, 30]]
print(result)
# [[11, 22, 33]
#  [14, 25, 36]]

[[11 22 33]
 [14 25 36]]


stacking


In [72]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# Vertical stacking (treats 1D arrays as rows)
vstacked = np.vstack((a, b))
print("Vertical Stack:\n", vstacked)

# Horizontal stacking (requires reshaping 1D arrays to 2D columns)
a_col = a.reshape(-1, 1)
b_col = b.reshape(-1, 1)
hstacked = np.hstack((a_col, b_col))
print("Horizontal Stack:\n", hstacked)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [[1 4]
 [2 5]
 [3 6]]


In [73]:
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])

concat_axis0 = np.concatenate((c, d), axis=0)
print("Concatenate (axis=0):\n", concat_axis0)

concat_axis1 = np.concatenate((c, d), axis=1)
print("Concatenate (axis=1):\n", concat_axis1)

Concatenate (axis=0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate (axis=1):
 [[1 2 5 6]
 [3 4 7 8]]


In [78]:
'''Create two 1D arrays with values from 1 to 6 (np.arange(1, 7)) and 7 to 12 (np.arange(7, 13)).
Reshape both into 2x3 arrays.
Stack them vertically to create a 4x3 array.
Split the resulting array into 2 equal parts along axis=0.
Print the stacked array, the split arrays, and the shape of the first split array.'''

arr1=np.arange(1,7)
arr2=np.arange(7,13)
Rarr1=arr1.reshape(2,3)
Rarr2=arr2.reshape(2,3)
vStacked=np.vstack((Rarr1,Rarr2))
print(vStacked)

split_array=np.split(vStacked,2,axis=0)
print("\nFirst split array:\n", split_array[0])
print("\nSecond split array:\n", split_array[1])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

First split array:
 [[1 2 3]
 [4 5 6]]

Second split array:
 [[ 7  8  9]
 [10 11 12]]


In [79]:


# Set seed for reproducibility
np.random.seed(42)

# 1. Basic Random Number Generators
print("2x3 uniform [0, 1):\n", np.random.rand(2, 3))
# Output: [[0.37454012, 0.95071431, 0.73199394],
#          [0.59865848, 0.15601864, 0.15599452]]

print("2x2 standard normal:\n", np.random.randn(2, 2))
# Output: [[ 0.05808361,  0.86617615],
#          [ 0.60111501, -1.01283112]]

print("2x3 integers [1, 10):\n", np.random.randint(1, 10, (2, 3)))
# Output: [[6, 3, 7],
#          [4, 6, 9]]

# 2. Sampling and Shuffling
arr = np.array([10, 20, 30, 40, 50])
print("Sample 3 elements with replacement:", np.random.choice(arr, 3))
# Output: [30, 10, 40] (varies without seed)

# Shuffle in place
arr_copy = arr.copy()  # Preserve original
np.random.shuffle(arr_copy)
print("Shuffled array:", arr_copy)
# Output: e.g., [20, 50, 10, 40, 30]

# Permutation (copy)
print("Permuted array:", np.random.permutation(arr))
# Output: e.g., [40, 10, 50, 30, 20]

# 3. Probability Distributions
print("2x2 uniform [5, 10):\n", np.random.uniform(5, 10, (2, 2)))
# Output: e.g., [[6.87230106, 9.75357154],
#                [7.99532932, 6.09966281]]

print("1x3 normal (mean=10, std=2):\n", np.random.normal(10, 2, 3))
# Output: e.g., [10.44386323,  9.27774428, 11.36463088]

print("1x3 Poisson (lam=4):\n", np.random.poisson(4, 3))
# Output: e.g., [4, 3, 5] (varies without seed)

2x3 uniform [0, 1):
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]
2x2 standard normal:
 [[ 1.57921282  0.76743473]
 [-0.46947439  0.54256004]]
2x3 integers [1, 10):
 [[5 1 6]
 [9 1 3]]
Sample 3 elements with replacement: [40 40 10]
Shuffled array: [20 40 50 10 30]
Permuted array: [40 20 30 10 50]
2x2 uniform [5, 10):
 [[9.74442769 9.82816017]
 [9.04198674 6.52306885]]
1x3 normal (mean=10, std=2):
 [10.582068    8.72888052  7.95689561]
1x3 Poisson (lam=4):
 [1 5 7]
